from django.core.management.base import BaseCommand
from store.models import Category, Product
from decimal import Decimal

CATEGORIES_DATA = [
    {
        "name": "Electronics & Gadgets",
        "slug": "electronics-gadgets",
        "products": [
            {
                "name": "Aero Pro Wireless Headphones",
                "slug": "aero-pro-wireless-headphones",
                "description": "Premium over-ear wireless headphones with active noise cancellation, 40-hour battery life, and high-fidelity sound.",
                "price": Decimal("199.99"),
                "old_price": Decimal("249.99"),
                "rating": Decimal("4.8"),
                "reviews_count": 342,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Pulse Smartwatch Series 7",
                "slug": "pulse-smartwatch-series-7",
                "description": "Advanced fitness smartwatch with AMOLED display, heart rate tracking, GPS, and 50m water resistance.",
                "price": Decimal("149.50"),
                "old_price": Decimal("189.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 215,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "SoundCore Mini Bluetooth Speaker",
                "slug": "soundcore-mini-bluetooth-speaker",
                "description": "Compact waterproof wireless speaker with dynamic bass, 15-hour playback, and rugged portable design.",
                "price": Decimal("45.00"),
                "old_price": Decimal("59.99"),
                "rating": Decimal("4.6"),
                "reviews_count": 188,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "UltraView 15.6 Inch 4K Portable Monitor",
                "slug": "ultraview-15-6-4k-portable-monitor",
                "description": "Ultra-slim 4K UHD external display with USB-C and Mini HDMI for laptops, gaming consoles, and mobile devices.",
                "price": Decimal("229.00"),
                "old_price": None,
                "rating": Decimal("4.9"),
                "reviews_count": 94,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "HyperCharge 65W GaN Wall Charger",
                "slug": "hypercharge-65w-gan-charger",
                "description": "Fast multi-port Gallium Nitride charger supporting fast charging for laptops, tablets, and smartphones.",
                "price": Decimal("34.99"),
                "old_price": Decimal("42.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 512,
                "is_new": False,
                "is_sale": True,
            },
        ],
    },
    {
        "name": "Men's Fashion",
        "slug": "mens-fashion",
        "products": [
            {
                "name": "Classic Oxford Cotton Slim-Fit Shirt",
                "slug": "classic-oxford-slim-fit-shirt",
                "description": "Tailored button-down oxford shirt crafted from 100% breathable organic cotton, versatile for office and casual wear.",
                "price": Decimal("48.00"),
                "old_price": Decimal("65.00"),
                "rating": Decimal("4.6"),
                "reviews_count": 120,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Heavyweight Fleece Pullover Hoodie",
                "slug": "heavyweight-fleece-pullover-hoodie",
                "description": "Ultra-soft fleece hoodie featuring kangaroo pocket, ribbed cuffs, and a modern relaxed silhouette.",
                "price": Decimal("58.50"),
                "old_price": Decimal("75.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 310,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Tailored Stretch Chino Trousers",
                "slug": "tailored-stretch-chino-trousers",
                "description": "Modern-cut chinos made with flexible cotton twill blend offering all-day mobility and polished smart-casual style.",
                "price": Decimal("54.00"),
                "old_price": None,
                "rating": Decimal("4.5"),
                "reviews_count": 89,
                "is_new": False,
                "is_sale": False,
            },
            {
                "name": "Vintage Washed Denim Trucker Jacket",
                "slug": "vintage-washed-denim-trucker-jacket",
                "description": "Timeless denim jacket made with rugged vintage wash, brass button hardware, and deep interior pockets.",
                "price": Decimal("89.99"),
                "old_price": Decimal("110.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 145,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Premium Supima Crewneck T-Shirt 3-Pack",
                "slug": "premium-supima-crewneck-tshirt-3pack",
                "description": "Three-pack of essential crewneck tees made from long-staple Supima cotton for exceptional durability and comfort.",
                "price": Decimal("39.00"),
                "old_price": Decimal("49.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 278,
                "is_new": True,
                "is_sale": False,
            },
        ],
    },
    {
        "name": "Women's Fashion",
        "slug": "womens-fashion",
        "products": [
            {
                "name": "Floral Print Summer Midi Dress",
                "slug": "floral-print-summer-midi-dress",
                "description": "Lightweight breezy midi dress with delicate floral motifs, adjustable tie waist, and flutter sleeves.",
                "price": Decimal("62.00"),
                "old_price": Decimal("85.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 194,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Oversized Chunky Knit Cardigan",
                "slug": "oversized-chunky-knit-cardigan",
                "description": "Cozy open-front cardigan sweater spun from soft wool-blend yarn with ribbed trims and drop shoulders.",
                "price": Decimal("52.00"),
                "old_price": Decimal("68.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 163,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "High-Waisted Wide-Leg Linen Trousers",
                "slug": "high-waisted-wide-leg-linen-trousers",
                "description": "Breathable linen-blend trousers featuring elasticated waistband, deep side pockets, and an effortlessly relaxed fit.",
                "price": Decimal("49.99"),
                "old_price": None,
                "rating": Decimal("4.6"),
                "reviews_count": 112,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "Elegant Silk-Blend Wrap Blouse",
                "slug": "elegant-silk-blend-wrap-blouse",
                "description": "Sophisticated V-neck wrap blouse with subtle satin sheen and flattering waist tie, ideal for day-to-night styling.",
                "price": Decimal("58.00"),
                "old_price": Decimal("72.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 86,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Cozy Ribbed 2-Piece Loungewear Set",
                "slug": "cozy-ribbed-2piece-loungewear-set",
                "description": "Ultra-comfortable matching top and wide-leg pant set crafted in buttery-soft ribbed knit fabric.",
                "price": Decimal("65.00"),
                "old_price": Decimal("80.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 220,
                "is_new": True,
                "is_sale": False,
            },
        ],
    },
    {
        "name": "Home & Living",
        "slug": "home-living",
        "products": [
            {
                "name": "Nordic Minimalist Ceramic Table Lamp",
                "slug": "nordic-minimalist-ceramic-table-lamp",
                "description": "Handcrafted ceramic table lamp with warm textured linen shade and dimmable ambient LED lighting.",
                "price": Decimal("64.00"),
                "old_price": Decimal("79.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 175,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Cloud Boucle Accent Armchair",
                "slug": "cloud-boucle-accent-armchair",
                "description": "Contemporary accent chair upholstered in plush ivory boucle fabric with ergonomic curve support.",
                "price": Decimal("289.00"),
                "old_price": Decimal("349.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 82,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Organic Washed Cotton Duvet Cover Set",
                "slug": "organic-washed-cotton-duvet-cover-set",
                "description": "100% certified organic washed cotton duvet cover with two matching pillow shams, naturally breathable and soft.",
                "price": Decimal("115.00"),
                "old_price": Decimal("140.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 140,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Ultrasonic Aromatherapy Essential Oil Diffuser",
                "slug": "ultrasonic-aromatherapy-essential-oil-diffuser",
                "description": "Whisper-quiet 500ml ultrasonic mist diffuser with ambient LED mood light and auto shut-off function.",
                "price": Decimal("38.50"),
                "old_price": Decimal("49.99"),
                "rating": Decimal("4.6"),
                "reviews_count": 290,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Handwoven Bohemian Jute Area Rug 5x7 ft",
                "slug": "handwoven-bohemian-jute-area-rug",
                "description": "Eco-friendly sustainable jute rug woven with subtle geometric accents to bring warmth and texture to any space.",
                "price": Decimal("135.00"),
                "old_price": None,
                "rating": Decimal("4.7"),
                "reviews_count": 67,
                "is_new": True,
                "is_sale": False,
            },
        ],
    },
    {
        "name": "Beauty & Personal Care",
        "slug": "beauty-personal-care",
        "products": [
            {
                "name": "Hydrating Hyaluronic Acid Serum",
                "slug": "hydrating-hyaluronic-acid-serum",
                "description": "Intensive moisturizing facial serum formulated with multi-molecular hyaluronic acid and vitamin B5 for plump skin.",
                "price": Decimal("26.00"),
                "old_price": Decimal("34.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 420,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Daily Invisible Mineral Sunscreen SPF 50",
                "slug": "daily-invisible-mineral-sunscreen-spf50",
                "description": "Non-greasy, broad-spectrum zinc mineral sunscreen that leaves zero white cast and protects against UV damage.",
                "price": Decimal("22.50"),
                "old_price": Decimal("28.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 310,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "Botanical Glow Facial Cleansing Oil",
                "slug": "botanical-glow-facial-cleansing-oil",
                "description": "Gentle nourishing cleanser with jojoba and rosehip oils to melt makeup and pollutants without drying skin.",
                "price": Decimal("29.00"),
                "old_price": Decimal("38.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 195,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Peptide Multi-Action Eye Repair Cream",
                "slug": "peptide-multiaction-eye-repair-cream",
                "description": "Rejuvenating eye cream infused with caffeine and peptides to visibly reduce dark circles, puffiness, and fine lines.",
                "price": Decimal("35.00"),
                "old_price": Decimal("45.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 152,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Organic Rosewater Balancing Face Mist",
                "slug": "organic-rosewater-balancing-face-mist",
                "description": "100% pure distilled damask rose water toner that refreshes, hydrates, and balances skin pH throughout the day.",
                "price": Decimal("18.00"),
                "old_price": None,
                "rating": Decimal("4.6"),
                "reviews_count": 130,
                "is_new": False,
                "is_sale": False,
            },
        ],
    },
    {
        "name": "Sports & Fitness",
        "slug": "sports-fitness",
        "products": [
            {
                "name": "Non-Slip High-Density Yoga Mat 6mm",
                "slug": "non-slip-high-density-yoga-mat",
                "description": "Eco-friendly TPE yoga mat with alignment guidelines, superior joint cushioning, and dual-sided non-slip grip.",
                "price": Decimal("36.00"),
                "old_price": Decimal("48.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 265,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Quick-Adjust Dumbbell Set 50 lbs",
                "slug": "quick-adjust-dumbbell-set-50lbs",
                "description": "Space-saving adjustable dumbbell with rapid dial mechanism ranging from 5 to 50 lbs for home strength workouts.",
                "price": Decimal("189.00"),
                "old_price": Decimal("229.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 178,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Insulated Stainless Steel Water Bottle 32oz",
                "slug": "insulated-stainless-steel-water-bottle-32oz",
                "description": "Double-walled vacuum insulated sports bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
                "price": Decimal("28.00"),
                "old_price": Decimal("35.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 380,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Deep Tissue Muscle Foam Roller",
                "slug": "deep-tissue-muscle-foam-roller",
                "description": "Textured trigger-point foam roller designed for post-workout recovery, myofascial release, and soreness relief.",
                "price": Decimal("24.50"),
                "old_price": None,
                "rating": Decimal("4.6"),
                "reviews_count": 142,
                "is_new": False,
                "is_sale": False,
            },
            {
                "name": "High-Speed Pro Cable Jump Rope",
                "slug": "high-speed-pro-cable-jump-rope",
                "description": "Lightweight steel cable jump rope with 360-degree ball bearings and ergonomic handles for speed cardio training.",
                "price": Decimal("16.99"),
                "old_price": Decimal("22.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 210,
                "is_new": True,
                "is_sale": True,
            },
        ],
    },
    {
        "name": "Books & Stationery",
        "slug": "books-stationery",
        "products": [
            {
                "name": "Hardcover Dotted Bullet Journal 160 GSM",
                "slug": "hardcover-dotted-bullet-journal-160gsm",
                "description": "Premium lay-flat hardcover notebook with bleed-resistant ultra-thick paper, pen loop, and dual bookmarks.",
                "price": Decimal("19.50"),
                "old_price": Decimal("25.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 315,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Solid Brass Weighted Rollerball Pen",
                "slug": "solid-brass-weighted-rollerball-pen",
                "description": "Precision-machined solid brass writing instrument that develops a unique vintage patina over time.",
                "price": Decimal("32.00"),
                "old_price": Decimal("40.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 168,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Waterproof Vegan Leather Desk Mat",
                "slug": "waterproof-vegan-leather-desk-mat",
                "description": "Large non-slip executive desk pad protecting surfaces while providing a silky smooth mouse glide surface.",
                "price": Decimal("27.00"),
                "old_price": Decimal("35.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 204,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Undated Productivity Daily Planner",
                "slug": "undated-productivity-daily-planner",
                "description": "Structured daily goal-setting planner with hourly schedules, habit trackers, and weekly review pages.",
                "price": Decimal("24.00"),
                "old_price": None,
                "rating": Decimal("4.8"),
                "reviews_count": 185,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "Precision Fine Liner Pen Set 12-Pack",
                "slug": "precision-fine-liner-pen-set-12pack",
                "description": "Archival quality pigment micro-pens with assorted tip sizes for technical sketching, illustration, and notes.",
                "price": Decimal("18.50"),
                "old_price": Decimal("24.00"),
                "rating": Decimal("4.6"),
                "reviews_count": 98,
                "is_new": False,
                "is_sale": True,
            },
        ],
    },
    {
        "name": "Footwear & Shoes",
        "slug": "footwear-shoes",
        "products": [
            {
                "name": "AeroFlex Lightweight Road Running Shoes",
                "slug": "aeroflex-lightweight-road-running-shoes",
                "description": "Responsive cushioned running shoes with breathable engineered mesh upper and durable shock-absorbing sole.",
                "price": Decimal("95.00"),
                "old_price": Decimal("125.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 274,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Classic Leather Casual Low-Top Sneakers",
                "slug": "classic-leather-casual-low-top-sneakers",
                "description": "Minimalist full-grain white leather sneakers with cushioned orthotic insole for timeless everyday smart style.",
                "price": Decimal("82.00"),
                "old_price": Decimal("105.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 320,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Weatherproof Suede Chelsea Boots",
                "slug": "weatherproof-suede-chelsea-boots",
                "description": "Handcrafted water-repellent suede ankle boots with elastic side gussets, pull tabs, and durable lug soles.",
                "price": Decimal("139.00"),
                "old_price": Decimal("175.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 146,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Knit Breathable Casual Slip-On Loafers",
                "slug": "knit-breathable-casual-slip-on-loafers",
                "description": "Featherlight slip-on shoes with flexible knit construction and memory foam arch support for comfortable walking.",
                "price": Decimal("68.00"),
                "old_price": None,
                "rating": Decimal("4.5"),
                "reviews_count": 88,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "CloudCushion Ergonomic Recovery Slides",
                "slug": "cloudcushion-ergonomic-recovery-slides",
                "description": "Thick-soled EVA recovery sandals designed with therapeutic arch support to relieve foot fatigue post-workout.",
                "price": Decimal("34.00"),
                "old_price": Decimal("45.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 190,
                "is_new": False,
                "is_sale": True,
            },
        ],
    },
    {
        "name": "Jewelry & Accessories",
        "slug": "jewelry-accessories",
        "products": [
            {
                "name": "18K Gold Vermeil Herringbone Chain Necklace",
                "slug": "18k-gold-vermeil-herringbone-chain-necklace",
                "description": "Sleek flat herringbone snake chain dipped in 18K gold over 925 sterling silver, hypoallergenic and non-tarnishing.",
                "price": Decimal("78.00"),
                "old_price": Decimal("98.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 185,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Classic Polarized Acetate Sunglasses",
                "slug": "classic-polarized-acetate-sunglasses",
                "description": "Handcrafted Italian acetate sunglasses featuring 100% UV400 polarized scratch-resistant lenses.",
                "price": Decimal("62.00"),
                "old_price": Decimal("80.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 160,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Slim RFID-Blocking Top Grain Leather Wallet",
                "slug": "slim-rfid-blocking-leather-wallet",
                "description": "Ultra-thin bifold wallet made from vegetable-tanned genuine leather with RFID-blocking protection.",
                "price": Decimal("44.00"),
                "old_price": Decimal("55.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 235,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Brushed Titanium Minimalist Cuff Bracelet",
                "slug": "brushed-titanium-minimalist-cuff-bracelet",
                "description": "Lightweight aerospace-grade titanium cuff bracelet with a satin matte finish, adjustable fit, and scratch resistance.",
                "price": Decimal("49.00"),
                "old_price": None,
                "rating": Decimal("4.6"),
                "reviews_count": 75,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "Chunky Gold Huggie Hoop Earrings",
                "slug": "chunky-gold-huggie-hoop-earrings",
                "description": "Timeless lightweight chunky huggie hoops with secure snap closure, waterproof and hypoallergenic for sensitive ears.",
                "price": Decimal("36.00"),
                "old_price": Decimal("48.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 210,
                "is_new": False,
                "is_sale": True,
            },
        ],
    },
    {
        "name": "Kitchen & Dining",
        "slug": "kitchen-dining",
        "products": [
            {
                "name": "Matte Black Gooseneck Pour-Over Electric Kettle",
                "slug": "matte-black-gooseneck-electric-kettle",
                "description": "Precision pour electric kettle with variable temperature control, LCD display screen, and rapid heating base.",
                "price": Decimal("52.00"),
                "old_price": Decimal("65.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 240,
                "is_new": True,
                "is_sale": True,
            },
            {
                "name": "Japanese Damascus Steel Chef Knife 8-Inch",
                "slug": "japanese-damascus-steel-chefs-knife-8inch",
                "description": "Hand-honed VG-10 cutting core with 67 layers of Damascus steel and ergonomic pakkawood handle for precision slicing.",
                "price": Decimal("89.00"),
                "old_price": Decimal("120.00"),
                "rating": Decimal("4.9"),
                "reviews_count": 310,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Pre-Seasoned Cast Iron Skillet 10.25-Inch",
                "slug": "pre-seasoned-cast-iron-skillet-10inch",
                "description": "Heavy-duty cast iron skillet offering superior heat retention and distribution, naturally non-stick and oven safe.",
                "price": Decimal("38.00"),
                "old_price": Decimal("48.00"),
                "rating": Decimal("4.8"),
                "reviews_count": 425,
                "is_new": False,
                "is_sale": True,
            },
            {
                "name": "Double-Walled Borosilicate Glass Coffee Mugs 4-Pack",
                "slug": "double-walled-glass-coffee-mugs-set",
                "description": "Insulated heat-resistant glass mugs that keep beverages hot while remaining cool to the touch on the outside.",
                "price": Decimal("29.50"),
                "old_price": Decimal("36.00"),
                "rating": Decimal("4.7"),
                "reviews_count": 180,
                "is_new": True,
                "is_sale": False,
            },
            {
                "name": "Organic Acacia Wood End-Grain Cutting Board",
                "slug": "organic-acacia-wood-cutting-board",
                "description": "Extra-thick solid acacia butcher block board with juice groove and side handles, gentle on knife blades and food safe.",
                "price": Decimal("34.00"),
                "old_price": Decimal("45.00"),
                "rating": Decimal("4.6"),
                "reviews_count": 155,
                "is_new": False,
                "is_sale": True,
            },
        ],
    },
]


class Command(BaseCommand):
    help = 'Seed database with 10 categories and 50 products'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Delete existing products and categories before seeding',
        )

    def handle(self, *args, **options):
        if options.get('clear'):
            self.stdout.write('Clearing existing products and categories...')
            Product.objects.all().delete()
            Category.objects.all().delete()

        cat_count = 0
        prod_count = 0

        for cat_data in CATEGORIES_DATA:
            category, created = Category.objects.get_or_create(
                slug=cat_data['slug'],
                defaults={'name': cat_data['name']},
            )
            if created:
                cat_count += 1
                self.stdout.write(f'Created category: {category.name}')
            else:
                category.name = cat_data['name']
                category.save()

            for prod_data in cat_data['products']:
                product, p_created = Product.objects.update_or_create(
                    slug=prod_data['slug'],
                    defaults={
                        'category': category,
                        'name': prod_data['name'],
                        'description': prod_data['description'],
                        'price': prod_data['price'],
                        'old_price': prod_data['old_price'],
                        'rating': prod_data['rating'],
                        'reviews_count': prod_data['reviews_count'],
                        'is_new': prod_data['is_new'],
                        'is_sale': prod_data['is_sale'],
                        'is_active': True,
                    },
                )
                if p_created:
                    prod_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully seeded database: {Category.objects.count()} categories and {Product.objects.count()} products.'
            )
        )
